### ISSUE TITLE
Implement Concourse CI pipeline

### ISSUE THREAD

**Issue by gbgdev** [fasd-club/fasd-bot#2]
The goal of this implementation is to place a CI process on the project while learning Concourse CI.

- [ ] Install Concourse CI on the server.
- [ ] Setup authentication with Github.
- [ ] Create a config YAML making the deploy happens every time the master branch gets updated.
